version: '3'

services:
  events-api:
    build: .
    image: yoonjae/events-api
    container_name: events-api
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5555:5000"
    networks:
      - airflow-network

networks:
  airflow-network:
    external: true